### ISSUE TITLE
Removal of gaming status 

### ISSUE THREAD

**Issue by crazyeee** [LongAKolangle/discord-owo-selfbot#30]
i know its your hard work and you deserve to be publicly advertised but that it self is super dangerous for owo players as anyone in their friends can view it and report it get banned

**Comment by LongAKolangle** [comment]
Since many people complained about the hunting activities, I've already shown a quick way to remove it in TSS (Tool Support Server discord)
Open index.ts file with text editor, find and remove the `reloadPresence(client)` line (as shown in the image)
For more FAQs and further explanation, please join our discord in the README.md

![image](https://github.com/LongAKolangle/discord-owo-selfbot/assets/101736195/d3871746-e7c4-4039-8c97-f5f385dd5ca1)
